name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
            pip install pylint
            pip install umsgpack
            pip install cryptography customtkinter
            pip install pylint-fail-under
      - name: Analyse code
        run: |
              for file in $(find . -name '*.py'); do pylint "$file" --fail-under=5.0; done
