name: Pylint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
            pip install pylint
            pip install umsgpack
            pip install cryptography
            pip install pylint-fail-under
        #lists pyling suggestions to improve the score & pylint score of the file
      - name: code review 
        run: find . -name '*.py' -print -exec pylint {} \;
        #fails the build if one file has pylint score below 7.0
      - name: Analyse code
        run: |
              for file in */*.py; do pylint "$file" --fail-under=6.0; done
